export const translations = {
  en: {
    brandTitle: "FeatureTree AI",
    brandSubtitle: "Local-first Feature Planner",
    workspaceProjects: "Workspace Projects",
    createNewProject: "Create new project",
    projectNamePlaceholder: "Project name...",
    projectDescPlaceholder: "Project description (optional)...",
    cancel: "Cancel",
    create: "Create",
    noProjectsYet: "No projects created yet. Click \"+\" or load seed data.",
    templatesQuickLoad: "Templates / Quick Load",
    loadParkingSample: "Load Parking Building Sample",
    clientRoleMetrics: "Client / Role Metrics",
    allClients: "All Clients",
    localBackup: "Local Backup",
    exportJson: "Export JSON",
    importJson: "Import JSON",
    searchPlaceholder: "Search features, rules, summaries, tags...",
    statusLabel: "Status:",
    priorityLabel: "Priority:",
    incompleteOnly: "Incomplete only",
    leafFeaturesOnly: "Leaf features only",
    interactiveFeatureTree: "Interactive Feature Tree",
    addChild: "Add Child",
    addSibling: "Add Sibling",
    totalFeatures: "Total features:",
    footerTip: "Press F2 to rename, Del to delete",
    noFeaturesFound: "No features found matching the filters.",
    adjustFilters: "Try adjusting your filters or search terms.",
    // Details
    nodeType: "Node Type",
    status: "Status",
    priority: "Priority",
    assignedClients: "Assigned Clients / Roles",
    summaryLabel: "Summary / Functional Description",
    summaryPlaceholder: "Describe what this feature accomplishes, the user story, or objective...",
    tagsLabel: "Tags (comma-separated)",
    tagsPlaceholder: "e.g. auth, api, settings",
    dependenciesLabel: "Dependencies (comma-separated)",
    dependenciesPlaceholder: "e.g. AUTH-LOGIN, PAYMENT-API",
    risksLabel: "Risks (comma-separated)",
    risksPlaceholder: "e.g. Third-party provider outage",
    notesLabel: "Notes & Technical considerations",
    notesPlaceholder: "Database references, links, libraries to use, or miscellaneous architectural constraints...",
    localBusinessRules: "Local Business Rules",
    newRulePlaceholder: "Add a new business rule local to this node...",
    noLocalRules: "No business rules are defined locally on this node.",
    add: "Add",
    inheritedAndEffectiveRules: "Inherited & Effective Rules (AI Export Context)",
    inheritanceDescription: "Child nodes automatically inherit all business rules of ancestor nodes. Below are the combined active rules that will be supplied to the AI.",
    localRulesLabel: "Local rules",
    inheritedFrom: "Inherited from",
    ruleCount: "rule",
    rulesCount: "rules",
    noRulesDescription: "No inherited or local rules govern this feature.",
    contractsDescription: "Define the contracts/schemas for this feature. These specifications provide deterministic boundaries when coding or verifying components.",
    apiContracts: "API Contracts",
    uiContracts: "UI Contracts / Layout Specs",
    dataContracts: "Data Models / DB Contracts",
    addSpec: "Add Spec",
    noSpecs: "No specs specified. Click \"Add Spec\" to document requirements.",
    testCasesSpec: "Test Cases Specification",
    addTestCase: "Add Test Case",
    noTests: "No tests are specified for this feature.",
    leafRequiresTests: "Leaf features require at least one test case to be marked AI-ready.",
    testTitle: "Test Title",
    testType: "Type",
    precondition: "Precondition",
    preconditionPlaceholder: "e.g. Database contains user record",
    steps: "Steps",
    addStep: "+ Add Step",
    stepPlaceholder: "Step",
    expectedResult: "Expected Result",
    expectedResultPlaceholder: "Expected behavior and output...",
    doneCriteriaChecklist: "Acceptance / Done Criteria Checklist",
    populateStandard: "+ Populate Standard Specs",
    newCriterionPlaceholder: "Add a new custom done criteria...",
    noDoneCriteria: "No done criteria specified.",
    clickPopulate: "Click \"Populate Standard Specs\" to load preloaded criteria.",
    selectScope: "1. Select Scope",
    exportMode: "2. Export Mode",
    copyClipboard: "Copy to Clipboard",
    copied: "Copied!",
    downloadMarkdown: "Download Markdown",
    markdownPreview: "Markdown Output Preview",
    singleNodeScope: "Single Node",
    subtreeScope: "Subtree",
    projectScope: "Full Project",
    aiMode: "AI View",
    humanMode: "Human Spec",
    qaMode: "QA Checklist",
    welcome: "Welcome to FeatureTree AI Planner",
    welcomeSub: "Create a new workspace project in the sidebar or click \"Load Parking Building Sample\" to start exploring.",
    noFeatureSelected: "No Feature Selected",
    selectNodeToEdit: "Select any node in the feature tree to view its metrics, edit requirements, define contracts, or generate AI prompt configurations.",
    aiReady: "AI-Ready",
    partiallyReady: "Partially Ready",
    notReady: "Not Ready",
    missingDetails: "missing detail",
    missingDetailsPlural: "missing details",
    allStatuses: "All Statuses",
    allPriorities: "All Priorities"
  },
  vi: {
    brandTitle: "FeatureTree AI",
    brandSubtitle: "Quản lý Cây Feature Offline",
    workspaceProjects: "Dự án Hiện tại",
    createNewProject: "Tạo dự án mới",
    projectNamePlaceholder: "Tên dự án...",
    projectDescPlaceholder: "Mô tả dự án (tùy chọn)...",
    cancel: "Hủy",
    create: "Tạo mới",
    noProjectsYet: "Chưa có dự án nào. Bấm \"+\" hoặc tải dữ liệu mẫu.",
    templatesQuickLoad: "Mẫu / Nạp nhanh",
    loadParkingSample: "Nạp Dữ liệu Mẫu Parking",
    clientRoleMetrics: "Thống kê Client / Vai trò",
    allClients: "Tất cả Client",
    localBackup: "Sao lưu Dữ liệu",
    exportJson: "Xuất file JSON",
    importJson: "Nhập file JSON",
    searchPlaceholder: "Tìm kiếm feature, rule, mô tả, tag...",
    statusLabel: "Trạng thái:",
    priorityLabel: "Độ ưu tiên:",
    incompleteOnly: "Chưa hoàn thiện",
    leafFeaturesOnly: "Feature lá",
    interactiveFeatureTree: "Cây Feature Trực quan",
    addChild: "Thêm Con",
    addSibling: "Thêm Cùng cấp",
    totalFeatures: "Tổng số feature:",
    footerTip: "Ấn F2 để sửa tên, Del để xóa",
    noFeaturesFound: "Không tìm thấy feature nào khớp với bộ lọc.",
    adjustFilters: "Thử thay đổi từ khóa hoặc các bộ lọc của bạn.",
    // Details
    nodeType: "Loại Node",
    status: "Trạng thái",
    priority: "Độ ưu tiên",
    assignedClients: "Client / Vai trò được gán",
    summaryLabel: "Tóm tắt / Mô tả chức năng",
    summaryPlaceholder: "Mô tả feature này làm gì, câu chuyện người dùng (user story), hoặc mục tiêu...",
    tagsLabel: "Tag (cách nhau bằng dấu phẩy)",
    tagsPlaceholder: "Ví dụ: auth, api, settings",
    dependenciesLabel: "Phụ thuộc (cách nhau bằng dấu phẩy)",
    dependenciesPlaceholder: "Ví dụ: AUTH-LOGIN, PAYMENT-API",
    risksLabel: "Rủi ro (cách nhau bằng dấu phẩy)",
    risksPlaceholder: "Ví dụ: Nhà cung cấp bên thứ 3 gián đoạn",
    notesLabel: "Ghi chú & Cân nhắc kỹ thuật",
    notesPlaceholder: "Các tham chiếu database, link tài liệu, thư viện sử dụng, hoặc ràng buộc kiến trúc...",
    localBusinessRules: "Luật Nghiệp vụ Nội bộ",
    newRulePlaceholder: "Thêm luật nghiệp vụ mới cho node này...",
    noLocalRules: "Chưa có luật nghiệp vụ nội bộ nào cho node này.",
    add: "Thêm",
    inheritedAndEffectiveRules: "Luật Kế thừa & Luật Hiệu lực (Context cho AI)",
    inheritanceDescription: "Các node con sẽ tự động kế thừa toàn bộ luật nghiệp vụ từ các node cha/tổ tiên. Dưới đây là danh sách luật hiệu lực sẽ gửi cho AI.",
    localRulesLabel: "Luật nội bộ",
    inheritedFrom: "Kế thừa từ",
    ruleCount: "luật",
    rulesCount: "luật",
    noRulesDescription: "Feature này chưa có luật nghiệp vụ nào được định nghĩa.",
    contractsDescription: "Định nghĩa các hợp đồng (contracts)/schemas cho feature này. Các đặc tả này tạo ranh giới rõ ràng khi dev code hoặc viết test.",
    apiContracts: "Hợp đồng API",
    uiContracts: "Đặc tả giao diện UI",
    dataContracts: "Mô hình Dữ liệu / DB",
    addSpec: "Thêm Đặc tả",
    noSpecs: "Chưa có đặc tả nào. Bấm \"Thêm Đặc tả\" để bắt đầu.",
    testCasesSpec: "Đặc tả các Kịch bản Test",
    addTestCase: "Thêm Kịch bản Test",
    noTests: "Feature này chưa có kịch bản test nào.",
    leafRequiresTests: "Feature lá cần có ít nhất một kịch bản test để được coi là Sẵn sàng cho AI (AI-ready).",
    testTitle: "Tên kịch bản test",
    testType: "Loại test",
    precondition: "Điều kiện tiên quyết",
    preconditionPlaceholder: "Ví dụ: Database đã có tài khoản user",
    steps: "Các bước thực hiện",
    addStep: "+ Thêm bước",
    stepPlaceholder: "Bước",
    expectedResult: "Kết quả mong đợi",
    expectedResultPlaceholder: "Mô tả hành vi và kết quả trả về...",
    doneCriteriaChecklist: "Checklist Tiêu chí Hoàn thành (Done Criteria)",
    populateStandard: "+ Nạp Tiêu chí Tiêu chuẩn",
    newCriterionPlaceholder: "Thêm tiêu chí hoàn thành mới...",
    noDoneCriteria: "Chưa có tiêu chí hoàn thành nào.",
    clickPopulate: "Bấm \"Nạp Tiêu chí Tiêu chuẩn\" để tải các tiêu chí mặc định.",
    selectScope: "1. Chọn Phạm vi",
    exportMode: "2. Chế độ Xuất",
    copyClipboard: "Sao chép Clipboard",
    copied: "Đã sao chép!",
    downloadMarkdown: "Tải file Markdown",
    markdownPreview: "Xem trước nội dung Markdown",
    singleNodeScope: "Node Hiện tại",
    subtreeScope: "Nhánh Con",
    projectScope: "Toàn bộ Dự án",
    aiMode: "Chế độ AI",
    humanMode: "Chế độ Người đọc",
    qaMode: "Checklist QA",
    welcome: "Chào mừng đến với FeatureTree AI Planner",
    welcomeSub: "Tạo dự án mới ở thanh bên trái hoặc bấm \"Nạp Dữ liệu Mẫu Parking\" để bắt đầu khám phá.",
    noFeatureSelected: "Chưa chọn Feature",
    selectNodeToEdit: "Bấm chọn một node bất kỳ trên cây feature để xem thống kê, sửa yêu cầu, định nghĩa contract, hoặc xuất prompt cho AI.",
    aiReady: "Sẵn sàng cho AI",
    partiallyReady: "Hoàn thành Một phần",
    notReady: "Chưa Sẵn sàng",
    missingDetails: "yêu cầu còn thiếu",
    missingDetailsPlural: "yêu cầu còn thiếu",
    allStatuses: "Tất cả Trạng thái",
    allPriorities: "Tất cả Độ ưu tiên"
  }
};
